### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by History-exe** [ttdyce/NHentai-NHViewer#12]
使用了最新版2.5.0sign版app后，不能刷新出任何内容。之前的2.4.0版本也不能加载内容。
我使用浏览器访问n站没问题，网络正常可以访问外网。
手机版本
一加3
Android9
lineageOS16

**Comment by ttdyce** [comment]
暫時沒遇過這個情況🤔
看看是不是網絡權限問題?

**Comment by History-exe** [comment]
早上又试了一下，莫名其妙正常了。:joy:

**Comment by History-exe** [comment]
@ttdyce 早上又试了一下，莫名其妙正常了。:joy:

**Comment by ttdyce** [comment]
ok!
