### ISSUE TITLE
The screenshots in .md crashed and about the translation

### ISSUE THREAD

**Issue by History-exe** [ttdyce/NHentai-NHViewer#14]
- There seems to be a problem with the picture preview in the md file and cannot be displayed normally.
- I would also like to ask if you need a Chinese translation. If necessary, I can help with the translation.

**Comment by ttdyce** [comment]
Thanks for the report, but I cannot find the broken part in the README.md. 
If you mean the blurry comic preview, that's normal since it is in demo mode! 

For the translation, Traditional Chinese is already included and it is enabled according to the device "Language" settings. 
Simplified Chinese is missing though, so I'm glad if you could help that part :)

**Comment by History-exe** [comment]
![The image](https://user-images.githubusercontent.com/33642965/88475667-ac24e600-cf64-11ea-81bc-6da944a45432.png)
Finally I learned how to add image in github issue.😂 Sorry for reply too late.

As the image above the image in .md file can't be displayed. My device is Ubuntu 20.04 and the browser is Firefox 78.0.2(64 bit). [This](https://github.com/agalwood/Motrix) project's image does't have the problem.

I refer to the traditional Chinese translation file naming and created a simplified Chinese translation file folder and create a pull request. I'm not used to using github, if there is a problem, you can change it at will.

**Comment by History-exe** [comment]
![zh-CN](https://user-images.githubusercontent.com/33642965/88477067-923cd080-cf6f-11ea-9d51-fef71e4730a1.png)
I found that there are a lot of simplified Chinese code names, but there are some mature projects that change the simplified Chinese code names to zh-CN. I am not sure whether to change the previous submissions to zh-CN. Everything is up to you.😂

**Comment by ttdyce** [comment]
I guess it is the OS's problem? 
I have tested on some browsers (Windows 10) and don't find the same issue. 
Maybe it is related to the image link, I am showing images in this repo but not uploading to githubusercontent.com

> Firefox, Windows 10 & Edge, Windows 10

<img src="https://user-images.githubusercontent.com/34944417/88477016-235f7780-cf6f-11ea-97e5-5587368c04c2.png" width="300"/><img src="https://user-images.githubusercontent.com/34944417/88477326-c0231480-cf71-11ea-95f1-f84c1d2d8853.png" width="300"/>

**Comment by History-exe** [comment]
Got it, thx.

**Comment by ttdyce** [comment]
Thanks for the reminder anyway!
Merging the translation now :)
