### ISSUE TITLE
Long "Loading from index" problem

### ISSUE THREAD

**Issue by huangguabaizhan** [ttdyce/NHentai-NHViewer#17]
index can not see anything。often“loading the index”。

**Comment by ttdyce** [comment]
yeah, it happens sometimes but I could not find the reason. 
Usually restarting the app, or wait for a while fixes the problem though 🤔

**Comment by huangguabaizhan** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tt"<notifications@github.com&gt;; 
发送时间: 2020年11月4日(星期三) 晚上9:30
收件人: "ttdyce/NHentai-NHViewer"<NHentai-NHViewer@noreply.github.com&gt;; 
抄送: "黄瓜百战依旧挺"<1351601369@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ttdyce/NHentai-NHViewer] problem (#17)





 
yeah, it happens sometimes but I could not find the reason.
 Usually restarting the app, or wait for a while fixes the problem though 🤔
