### ISSUE TITLE
About "android.permission.CAMERA"

### ISSUE THREAD

**Issue by theFreeWall** [ttdyce/NHentai-NHViewer#18]
For such an app, requesting camera permissions is very sensitive.
This may cause some people to refuse to use this app.
From the source code, we can know that the camera is used to read the QRcode.
But for most users, they dont have the ability to review the code.(Many people don’t even know what is Open Source Software.) They will be worried when the phone tells them that this app want to use the camera.
A popularity of similar app,"ehviewer" relies on its convenient operation and open source transparency. It requires very few permissions, so people don't have to worry about apps secretly taking pictures while doing SOMETHING.    (′▽`〃)
Search book by ID has been added in the latest update, maybe the QRcode function is no longer needed?

**Comment by ttdyce** [comment]
This is actually a good point! 

The camera permission is for another project [ttdyce/NHV-Backup](https://github.com/ttdyce/NHV-Backup)
By scanning a QRCode there, the app backup all collections and history to the desktop computer
so I think it is still needed for that part. 

I planned to update the permission request part later to keep this functionality while also protect privacy. 
I will only ask for permission from those who click the "scanning QRCode" button, thanks!
