### ISSUE TITLE
Can't connect the home page in nhviewer

### ISSUE THREAD

**Issue by Apurikotto** [ttdyce/NHentai-NHViewer#25]
![Screenshot_2022-05-30-09-05-17-611_com github ttdyce nhviewer](https://user-images.githubusercontent.com/72537772/170900095-e40550ad-f63f-4a19-b56f-288564237b38.jpg)
Hi, i can't connect the home page from yesterday, when i start the app, it's always been like the screenshot, i only can use the favourite and i also can click inside.
![IMG_20220530_090557](https://user-images.githubusercontent.com/72537772/170900287-b327e71e-91d7-49e1-88c8-1d54ccb28fb2.jpg)
I can connect NH in browser, should i have to uninstall the app? i'm afraid it will delete my favourite.

**Comment by ttdyce** [comment]
yes, It is a known issue I found recently (see #24 or [more detailed post](https://ttdyce.com/2022/05/17/NHentai-API-site-update-issue/))
In short, sometimes the website is being blocked and makes this app failed to get data from it. 
I will try to fix it later, if possible 😵‍💫

**Comment by Apurikotto** [comment]
I looked at #24 before and just thought it wasn't the same issue. Thank you so much for your reply.
