### ISSUE TITLE
Endless Loading from index messge

### ISSUE THREAD

**Issue by aknight2015** [ttdyce/NHentai-NHViewer#26]
When the app starts it just displays "Loading from index" endlessly.

**Comment by ttdyce** [comment]
🤔 Have you wait for 5s in the "loading" screen? 
It is required due to the recent nhtentai update.

**Comment by aknight2015** [comment]
Yeah. I'm used to that sort of thing. I actually gave it around 30+ seconds. They have a check now to make sure your browser is secure before letting you in. Maybe that's the issue?

**Comment by aknight2015** [comment]
I get to the second page and nadda.

**Comment by partial-derivative** [comment]
same question

**Comment by ttdyce** [comment]
I have tested on my phone and Android emulator but both of them are working. 
Is it possible to reproduce in Android emulator?
I wonder if it is Android device issue or Networking issue

**Comment by aknight2015** [comment]
Alright. I ended up doing a Factory Reset on my tablet. It needed it. I updated from Android 11 to 12, and just had a massive security update. So you're app is working perfectly. The issue was due to the updates.

**Comment by ttdyce** [comment]
ok, thanks for the update!
