### ISSUE TITLE
human checking读取cookie太快导致访问失败

### ISSUE THREAD

**Issue by Apurikotto** [ttdyce/NHentai-NHViewer#27]
是这样的，新版本更新了cf的连接验证，不知道是不是我的问题，我每次都会转到人工验证，但是人工验证需要点击我不是机器人之后才会正确读取cookie，每次还没等到那个地方弹出来，app就说自动获取了cookie然后验证失败
![Uploading Screenshot_2023-05-12-19-02-27-727_com.github.ttdyce.nhviewer.jpg…]()
![Uploading Screenshot_2023-05-12-19-02-36-372_com.github.ttdyce.nhviewer.jpg…]()
![Uploading Screenshot_2023-05-12-19-02-39-324_com.github.ttdyce.nhviewer.jpg…]()

**Comment by Apurikotto** [comment]
![Screenshot_2023-05-12-19-02-27-727_com github ttdyce nhviewer](https://github.com/ttdyce/NHentai-NHViewer/assets/72537772/5a61d5d2-7521-43aa-88f0-ff673bb60075)
![Screenshot_2023-05-12-19-02-36-372_com github ttdyce nhviewer](https://github.com/ttdyce/NHentai-NHViewer/assets/72537772/6bf94d06-1da4-4e58-ae67-44a1093d9ec3)
![Screenshot_2023-05-12-19-02-39-324_com github ttdyce nhviewer](https://github.com/ttdyce/NHentai-NHViewer/assets/72537772/c7f7a6d1-8461-4551-8170-a03ecb2f781e)

**Comment by ttdyce** [comment]
For now, try clicking this button in Settings, and then go to Home page. 
I sometime find this error too, still checking 🤔
Thanks for the report. 
![Screenshot_20230513_185400](https://github.com/ttdyce/NHentai-NHViewer/assets/34944417/2ff55625-55c0-42a4-92de-0c2244ac3cf3)

**Comment by Apurikotto** [comment]
I know that, but when I click refresh, it did not refresh the cookie as expected, but directly saved the cookie. I'm not sure what's going on, but I hope the issue can be fixed.
Thanks.
![Screenshot_2023-05-13-19-27-41-860_com github ttd](https://github.com/ttdyce/NHentai-NHViewer/assets/72537772/ad5156a2-aa3e-4a20-8d00-9f19ea33f886)

**Comment by ttdyce** [comment]
Ok, I will keep track this issue here. 
Thanks.

**Comment by ttdyce** [comment]
New version (3.3.2) will clear cookie when clicking "refresh cookie" now, you may try again. 
Also, it is normal that  "... use manual mode" may not require you to click "I'm not robot". I may clarify the wording later. 
Thanks.

**Comment by Apurikotto** [comment]
> New version (3.3.2) will clear cookie when clicking "refresh cookie" now, you may try again. Also, it is normal that "... use manual mode" may not require you to click "I'm not robot". I may clarify the wording later. Thanks.

Sorry for the late reply, refresh cookie now works better than the previous version.
Thanks for keeping on top of this issue.
